import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (             //layout for every page
    <html lang="en">
      <body className={inter.className}>
        <div className="p-4 border-b">
          Medium Website
        </div>
        
        {children}
        </body>
    </html>
  );
}

//if i put hi there above {children},hi there will be visible on every route
//similarly the above divbar will be there for every page 

